openapi: 3.0.0
info:
  title: Customer Management API
  version: 1.0.0
paths:
  /customers:
    post:
      summary: Create a new customer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
      responses:
        '201':
          description: Customer created
        '400':
          description: Invalid request
  /customers/{id}:
    get:
      summary: Retrieve a customer by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Customer retrieved successfully
components:
  schemas:
    CustomerRequest:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        annualSpend:
          type: number
        lastPurchaseDate:
          type: string
          format: date-time
